### ISSUE TITLE
지금 구조에 대한 치명적인 문제점에 대한 고찰

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#115]
예를들어 read file을 하다가 에러가 생겨서 에러페이지를 open해 read를 또 해야하는 상황이 생긴다면 
Next state가 read기 때문에 이벤트 등록이 안된다

Recv requset같은 경우는 한 이벤트에서 같은 fd로 이벤트가 발생하니 추가해줄 필요 없지만, read일때 한번더 생기면 그때 문제가 생김

각 state마다 발생되는 경우의 수가 달라서 if (nextstate != currstate)로 묶으면 안될듯함

해결책
1) 그냥 각 state마다 경우의 수에 따라 이벤트 등록해줘야할듯?

2) 아니면 그대로 두고 continue state를 새로 만들어서 구분을 해줌

3) ~아니면 아예 read할때 error가 생길때 send response로 가서 errorpage read 해도됨~ (근데 response message를 다 만들어서 send response로 가는게 맞는듯)

**Comment by minjune8506** [comment]
그럼 어제 지현님이 말씀하신대로 kq handler 주고나서 알아서 처리하게 되면은 해결이 되는 문제인가요??

**Comment by zhy2on** [comment]
흠 그럼 READ_FILE, READ_ERROR_PAGE 이런 식으로 상태 나눠야 할 것 같아요

**Comment by zhy2on** [comment]
아 kq handler를 주면 알아서 처리할 수 있을 것 같아요
