### ISSUE TITLE
Map insert할때 레퍼런스로 전달 가능?

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#117]

**Comment by minjune8506** [comment]
socket *으로 할건데 굳이 레퍼런스로 할 이유가 있나요

**Comment by u-lo-l** [comment]
map<int, ClientSocket&> 로 하면 new안하고 가지고 다닐 수 있지 않을까? 라고 생각했는데 아닌거 같네요. 동적 할당이 맞는 것 같습니다.
