### ISSUE TITLE
ServerInfo 객체에 필요한 것들

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#143]
server location 비교해서 ~
- [x] std::string GetRoot() (root 반환, 만약 없다면 default값)
- [x] std::string GetPath() (path 반환 만약 server이면 빈 문자열)
- [x] bool IsIndex() (bool 반환 server client 중 하나라도 있으면 true)
- [x] bool IsAutoIndex() (bool 반환 server client 중 하나라도 있으면 true)
- [x] std::vector<std::string> GetIndex() (server location 비교해서 index vector)
- [x] bool IsCGI() (server location 비교해서 cgi 있으면 true)
- [x] std::vector<std::string> GetCGI (server location 비교해서 cgi 있으면 GetCGI)
- [x] bool IsRedirect() (server location 비교해서 redirect true / false)
- [x] std::string GetRedirect() (server location 비교해서 redirect string)
 부탁 드립니다 흐흐

**Comment by keonwoo98** [comment]
- [ ] Default error page string으로 저장
