### ISSUE TITLE
<request> nc -c localhost... 로 테스트 시 Sigfault 발생 

### ISSUE THREAD

**Issue by maindishes** [keonwoo98/webserv#154]
- nc -c localhost ~ 로 테스트 시  예외 발생합니다 
- minjune님이 예외 처리를 해놔서 requset 단에서 한번 직접 테스트 해보시고 에러 헨들링 부탁합니다!

**Comment by u-lo-l** [comment]
에러가 나서 예외처리로 일단 에러 안 나게 막아둔건가요?

**Comment by u-lo-l** [comment]
지금 develop에서 nc -c localhost로 테스트 할 때 sigfault안 나는거 같은데 어떤 상황에서 났는지 기억 나시나요?

**Comment by maindishes** [comment]
bind 에러시 포트 사용중인지 확인 해보기
lsof -Pni4 | grep LISTEN
