### ISSUE TITLE
cgi handler 좀비 프로세스 문제

### ISSUE THREAD

**Issue by zhy2on** [keonwoo98/webserv#170]
## 문제
cgi 로직에서 자식 프로세스를 만들게 되는데,
부모 프로세스보다 자식 프로세스가 먼저 죽어 좀비 프로세스가 생기게 됨.

보통은 wait로 자식 프로세스가 종료될 때까지 기다렸다가 자식 프로세스의 종료 상태를 회수해 좀비프로세스를 막지만
wait가 블락킹이기 때문에 webserv에서는 사용할 수 없음.

해결 방법은 무엇일까?

1. 자식 프로세스가 이미 끝났을 시점에서 waitpid(자식프로세스 pid, 0, WNOHANG) 로 상태 회수. -> 자식 프로세스의 pid를 보관하고 있어야 함
2. 자식 프로세스가 이미 끝났을 시점에서 waitpid(-1, 0, WNOHANG) 로 상태 회수. 어차피 만든 자식 프로세스가 하나니까 -> 이상하게 이미 childCgi가 종료했을 시점에서 시도를 해도 한 번에 성공을 못 함. 이유가 뭘까
3. SIGCHILD 시그널 무시? (테스트 필요)

<img width="269" alt="image" src="https://user-images.githubusercontent.com/52701529/210075496-afd126aa-fa23-4d7f-92af-932bf85bfdbd.png">

## 새로 찾은 이상한 점
생각해보면 부모 프로세스에서 cgi를 fork해서 사용할 때마다 새로운 자식 프로세스를 만드는 것이고,
그 때마다 좀비 프로세스가 하나씩 늘어나야 할텐데
새로 cgi를 fork해서 사용하면 이전 좀비 프로세스는 사라지고 새로운 좀비 프로세스 하나로 대체됨

**Comment by minjune8506** [comment]
자식 프로세스가 종료되면 EV_EOF에서 걸리게 될 것 같은데 이때 처리해보는건 어때요?

**Comment by minjune8506** [comment]
cgi response를 모두 읽게 되면 EV_EOF로 오긴 올테고
그 경우는 자식 프로세스가 종료되었다고 알 수 있다? 라고 정확하지는 않는데 생각만 해봤습니다.

**Comment by zhy2on** [comment]
음 한 번 해보겠습니다

**Comment by zhy2on** [comment]
흠.. 그래도 똑같네요
원래 pipe read의 리턴 값이 0이면 파이프의 EOF 까지 읽은 것이고 그 말은 자식 프로세스가 파이프에 쓰기를 끝낸 이후여서
read 리턴값이 0인 것과 EV_EOF 플래그가 발생했을 때가 똑같은 경운데

두 경우 모두 waitpid(-1, 0, WNOHANG) 으로 논블럭킹으로 검사해주면 한 번에 성공하지 못 합니다ㅠㅠ

이상한 게 하나 더 있는데 fork 한 자식 프로세스 종료상태를 회수 하지 않아 좀비 프로세스가 생긴 거라면
cgi를 실행할 때마다 좀비 프로세스가 하나씩 늘어나야 하는데
새로 cgi를 실행하면 이전 좀비 프로세스는 자동으로 없어지고, 새로운 좀비 프로세스로 대체됩니다..

이유는 일단 제가 찾아보고 있겠습니다

**Comment by minjune8506** [comment]
EVFILT_PROC
kqueue reference에서 이거 한번 읽어보세여

**Comment by minjune8506** [comment]
A "zombie process" is a process that has completed execution but still has an entry in the process table, allowing the parent process to read its exit status. 

kqueue에서 event가 나오기 전까지는 zombie process가 되는것이 어떻게 보면 당연한거 같기도 하고...

**Comment by zhy2on** [comment]
와대박 생각해보니 kqueue에 pid도 등록할 수 있었네요

**Comment by zhy2on** [comment]
으음... 근데 자식 프로세스에서 getpid를 해서 kqueue에 등록하자니 kqueue는 fork로 전달이 되지 않아서 안 되고,
부모 프로세스에서 자식 프로세스의 pid를 kqueue에 등록하자니 자식 프로세스가 부모 프로세스에게 자신의 pid를 전달해줘야 알 수 있네요..

**Comment by minjune8506** [comment]
fork하면 부모 프로세스에 자식 프로세스 pid 전달되지 않나요??

**Comment by zhy2on** [comment]
대박 그러네요... 완전 잊고 있었네요 얼른 고쳐서 올려놓겠습니다..

**Comment by zhy2on** [comment]
#175
