### ISSUE TITLE
Config 요청사항

### ISSUE THREAD

**Issue by minjune8506** [keonwoo98/webserv#171]
- [x] Allow Method 클래스화 (option)

- [x] IsAllowedMethod 메서드 기능 개발
input : method
return bool
혀용된 메서드인지 확인하고 true / false
location block server block 두개 고려해서 반환해 주세요
``` C++
bool IsAllowedMethod(std::string method) {
};
```

- [x] 지금 main.cpp 파일을 보면 server_configs 변수밖에 쓰이지 않고 있음 server_blocks는 내부적으로 처리하고 server_configs를 반환하도록 하면 될 것 같음
-  [ ] ConfigParser 내부에서 저장하고 있는 변수(config 문자열)이 파일 open하는데만 쓰인다면 ConfigParser의 static 메서드로 parse를 만들고 객체를 생성할 필요 없이 바로 parsing하고 결과를 반환해도 좋을 것 같음

**Comment by maindishes** [comment]
location block server block 두개 고려해서 반환해 주세요  
-> allow_methods 인 limit_except 옵션은 location block 에만 있습니다.

**Comment by minjune8506** [comment]
@maindishes 음 그럼 server_info에서 string으로 method를 넣었을때 이게 허용되는 method인지 리턴해주세여

**Comment by maindishes** [comment]
마지막은 요구 사항은 config 에 파일 에서 읽은 한줄한줄 데이터가 저장 되므로 Pass ~
