### ISSUE TITLE
X-Powered-By, Server header 보안 취약점 이슈

### ISSUE THREAD

**Issue by zhy2on** [keonwoo98/webserv#177]
X-Powered-By, Server header 관련 검색하다가 발견한 보안 취약점 내용 이슈로 공유해봅니다
보통 서버 개발할 때 위 헤더는 보안 취약점을 만들 수 있어 일부러 보내지 않는 경우가 있다고 하네요

## 문제
``X-Powered-By`` 헤더와 ``Server``헤더는 클라이언트 측에서 알게 되면 공격하기 쉽게 정보를 제공하는 꼴이 될 수 있다고 함.

👉 이슈 설명 블로그: https://mygumi.tistory.com/92, https://velog.io/@mer1-97/%EC%84%9C%EB%B2%84-%EC%A0%95%EB%B3%B4-%EB%85%B8%EC%B6%9C-%EC%B7%A8%EC%95%BD%EC%A0%90-ju3lyymb

## 해결법
``X-Powered-By`` 헤더는 지금 php-cgi를 실행시켰을 때 나오게 되는데,
php.ini에서 ``expose_php = Off``로 바꾸면 막을 수 있음.

👉 php.ini위치: https://zetawiki.com/wiki/Php.ini%EC%9D%98_%EC%9C%84%EC%B9%98

``Server`` 헤더 같은 경우 nignx에서는 설정을 통해 response header에 server 정보를 노출 시킬 것인지 정할 수 있다고 함.
webserv에서는 그냥 보내도 될 것 같긴 함

**Comment by minjune8506** [comment]
X-powered-By 헤더는 cgi response로 나오는데 파싱할때 무시해버리는건 어떨까요

**Comment by zhy2on** [comment]
음 php.ini에서 ``expose_php = Off``로 설정 하면 안 나오긴 하는데
나와도 무시해버리게 처리해 놓겠습니답
