### ISSUE TITLE
nginx 에서 디렉토리 접근할때 신기한점

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#197]
auto index off
index 설정안하고

디렉토리에 접근하려고하면, 그냥 아무 파일 없으면 403 보내고, index.html이 있으면 그 파일을 보여줌... 근데 index.html이 아닌 다른 애들은 또 403으로 보여줌... 문제는 index 설정도 안하고 auto index도 없는데, 
server에서 index 이미 디폴트로 설정되어있는 건가

결론
 index 설정 안되어있으면 디렉토리 접근할때 무조건 안에 있는 index.html있는지 확인후 넣어줘야함

**Comment by maindishes** [comment]
- 설정해 드렸습니다~
