### ISSUE TITLE
servers vector 중복 address 관련 문제

### ISSUE THREAD

**Issue by zhy2on** [keonwoo98/webserv#42]
## 문제
``` c
server {
	server_name webserv;
	listen 0.0.0.0:4242;
...
}

server {
	server_name another_webserv;
	listen 0.0.0.0:4242;
...
}
```

config file이 위와 같은 경우 server vector에 0.0.0.0:424(host:port)가 중복 되어 들어가게 됨.

```cpp
for (size_t i = 0; i < servers.size(); ++i) {
		Server item = servers[i];
		ServerSocket *server = new ServerSocket(item.GetHost(), item.GetPort());
		server->ReadyToAccept();
		AddServerKevent(server);
}
```
host:port를 servers 벡터를 돌며 bind 하려 할 때, 중복된 address 때문에 ``Address already in use`` error가 발생하게 됨.
<img width="266" alt="image" src="https://user-images.githubusercontent.com/52701529/208229518-fc784915-d921-47b1-a949-11d72d0a69cb.png">

## 해결안
1. servers vector를 map으로 관리. key는 host:port. value는 configs (vector type)
2. server_socket에서 주소를 bind할 때 이미 open한 address는 건너뛰기

**Comment by maindishes** [comment]
config 파싱할때 수정하는게 1번 맞을까요? 맞으면 value 값 configs (vector type) 이 뭔지 부연 설명 가능할까요 ?

**Comment by zhy2on** [comment]
1번과 2번 중에 아직 어떤 걸로 할지 선택하진 않았는데, 1번을 사용하게 된다면
map의 첫 번째 인자인 key 값으로 <host, port>를 사용하고, value 값으로는 <host, port>를 제외한 server block들을 넣어주면 될 것 같습니다.

그니까 같은 host:port당 여러 서버 블락들이 있을 수 있는데, bind할 때는 여러 서버 세팅이 있어도 하나의 host:port만 열 수 있으니까
key로 host:port를 사용하고
value로는 해당 host:port와 매핑되는 server block 세팅들을 vector로 쭉 넣어주면 되지 않을까.. 하는 생각입니다.

근데 복잡해서 일단 보류하고 테스트 중입니다ㅠㅠ 중복은 나중에 해결해도 될 것 같아서요..

**Comment by maindishes** [comment]
#55
