### ISSUE TITLE
config/server class 구조 

### ISSUE THREAD

**Issue by maindishes** [keonwoo98/webserv#55]
key------set
<host:port>  server_name
                      server_name
                         ....

데이터 구조 바꿔서 저장 하기 왜냐면 host:port 의 키값이 같은게 있을수있는데 bind 하게 되면 이미 있는 키값은 bind error 난다. 그래서 이런 구조로 바꾸려는것 #42  의 해결 방안 1.)

server_name 이 같을 경우 -> host:port 가 다를 때 
둘다 같으면 첫 번째만 유호하고 나머지 무시 

반론. server_name 을 key값으로 하자.
request 의 호스트가 a -> server_name 이 a 인걸 찾아야 하는데 자기가 어떤 <host:port> 그게 뭔지 알수가 없다. 
->listen socket 에서 역추적 하면 되는거 아니냐 ?  
->client_socket 안에 생성한 서버네임 리스트를 가지고 있어야 한다.

-> 그냥 클라이언트 소켓한테 server_name 리스트만 가지고 있으면 된다.

즉 그냥  config 팀은 처음 형태로 하면 된다.

**Comment by keonwoo98** [comment]
std::map<std::string, std::string> host_port;
std::set<std::string> server_name;
std::multimap<std::map<std::string, std::string>, std::set<std::string>> host_port_server_name;

**Comment by maindishes** [comment]
use_map 의 타입은 std::map<std::string, std::vector<ServerInfo> > 로 저장했습니다.
이 맵의  key 값은 host + : + port 입니다.
