### ISSUE TITLE
Config file client_max_body_size error document

### ISSUE THREAD

**Issue by maindishes** [keonwoo98/webserv#57]
Syntax: | client_max_body_size size;
-- | --
client_max_body_size | 1m;

- Sets the maximum allowed size of the client request body. If the size in a request exceeds the configured value, the 413 (Request Entity Too Large) error is returned to the client. 
- Please be aware that browsers cannot correctly display this error. Setting size to 0 disables checking of client request body size.

[config reference](https://nginx.org/en/docs/http/ngx_http_core_module.html#http)

**Comment by u-lo-l** [comment]
1. conf파일이 파싱되면 conf파일 내의 서버블럭 개수 만큼 Server객체가 생성된다.
2. 각 Server객체는 <host:port>, server_name들, auto_index여부, max_content_size등의 정보를 담고있다.
3. 지금은 Server객체의 host, port만을 이용하여 ServerSocket을 생성하는데, 이를 Server객체를 이용하여 생성하도록 변경한다.
4. 이 중 max_content_size, allowed_method는 request_message를 파싱하는 데 필요한 정보이다.
5. requset_message는, ClientSocket의 객체이고 ClientSocket을 생성할 때, Server객체가 가지는 정보의 일부를 넣어주면 참고할 수 있을 것 같다.
6. 지금 ClientSocket이 생성되는 부분은 ServerSocket에서 accept()가 호출된 뒤에 위치한다
7. 이 때 지금 fd값만으로 ClientSocket이 생성되는데, fd와 함께 ServerSocket객체가 가지고 있던 Server객체를 같이 넘겨줘서 ClientSocket이 서버 블럭 정보를 가질 수 있게 한다.
8. Client소켓이 서버블럭정보를 가지고 있다면 request나 response에서 서버블럭의 정보를 이용하기 용이할 것 같다.
