### ISSUE TITLE
Config file 예외처리

### ISSUE THREAD

**Issue by keonwoo98** [keonwoo98/webserv#68]
1. port 번호가 PORT_MAX인 65535을 넘는 경우
2. 이미 사용중인 포트로 시도 시, 서버 다운

**Comment by zhy2on** [comment]
음 2번은 ServerSocket에서 bind 하다가 실패했을 때 SocketError로? 처리해주면 될 것 같습니다!
1번만 config 단에서 처리해주심 될 것 같습니다

**Comment by keonwoo98** [comment]
> 음 2번은 ServerSocket에서 bind 하다가 실패했을 때 SocketError로? 처리해주면 될 것 같습니다! 1번만 config 단에서 처리해주심 될 것 같습니다

네 알겠습니다!

**Comment by minjune8506** [comment]
@zhy2on 2번은 제가 지금 처리하고있어서 제가 해놓겠습니다.

**Comment by zhy2on** [comment]
넵 알겠습니다!
