### ISSUE TITLE
Conf/Serverblock~

### ISSUE THREAD

**Issue by maindishes** [keonwoo98/webserv#82]
- [x] Server Blocks 안에는 allow_method 아예 지워버려야한다 
  -  nginx 설정 자체도 Sever Blocks 안에 allow_methods(limit_except)가 존재할수 없다. 
- [x] vector로 정의된 멤버변수들을  클래스화 시켜서 refactoring 요청. ( 블럭 하나만 쓰일경우는 따로 클래스로 안 만들어도 될것)
  - 예를 들어 index 같은 겨우 공식 레퍼런스에 http , server, location 블락에 모두 쓰이는데 이런 경우 객체로 만들면 쓰기 편할것이다
  - -[x] location에도 error_page 있어야 한다. 

[객체지향](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)
[일급클래스란?](https://jojoldu.tistory.com/412)
객체가 일 하게 하라.

** TEST unitest  는 선택이 아닌 필수이다.  **

**Comment by u-lo-l** [comment]
- Server Blocks 안에는 allow_method 아예 지워버려야한다 <- 그럼 allowed method는 아예 없어지나요?

**Comment by maindishes** [comment]
아니요 location block 안에는 남아있습니다!. 
원래 nginx 레퍼런스에 메소드 허락하는 옵션은 limit_except 이라는 얘인데 저희는 그냥 allow_methods 라고 정해놓고 파싱했습니다.
근데 limit_except 이라는 옵션이 nginx 레퍼런스에 location block 에만 해당하는 옵션입니당
