### ISSUE TITLE
nginx 테스트 결과들

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#89]
1)
  `/opt/homebrew/Cellar/nginx/1.23.2/bin`
  이 안에 nginx 실행파일이 있음 따라서 root를 `./`로 설정하면
  `/opt/homebrew/Cellar/nginx/1.23.2` 
  이 위치를 가리킴
  
  _nginx 환경에 따라 다를것 같은데, 일단 우리 웹서브 입장에서 `./`로 root를 설정하면  webserv 실행파일의 `../` 경로를 가리켜야 할것 같다_
  그냥 폴더안을 가르킬 예정

2) server root와 location root 에 각각 같은 이름의 디렉토리가 있어도 location이 디렉토리 이름이면 무조건 로케이션꺼로 들어감

예를들어 
지금 폴더가, `/var/www/a/index.html`이렇게도 있고, `/User/seungsle/a/index.html` 이렇게도 있을때

conf 가 이렇게 설정된다면,
```
server {
  root /var/www;

  location /a {
    root /User/seungsle;
  }
}
```
loaction 부터 본다.

~~3) root  ""; 이 경우와 root 가 없는 경우를 분리해서 알아야한다 (conf team)~~
```
server {
  root "";

}
```
~~이 경우는 root 가 존재~~

```
server  {
  # root "" ;

}
```
~~이 경우는 root 가 존재x -> (default)~~
알고보니 root 없는거든 root에 "" 들어가든 무조건 default이였다라는 결론

**Comment by aLVINlEE9** [comment]
@maindishes 여기 테스트 결과 추가해 주세요~

**Comment by keonwoo98** [comment]
전제 조건  uri 가 location path보다 같거나 길어야 한다. 
ex ) uri : http://localhost:8000/a/b/c          config : location a/b/c/d { } 이면  이 블락으론 절대 안 들어간다!. ->일치하는 location 블락이 없고->  location / {} 이 블락이 있으면 여기 블락으로 들어가고 없으면 -> server 블락으로 간다
 (우리는 -1 리턴)

1) uri == location path  
ex )  http://localhost:8000/a/b/c      ==   location a/b/c {}      

2) uri > location path 
ex )  http://localhost:8000/a/b/c     > location /a/b {}   (V)   or       location /a {}  (X)    이면 첫번째 location 블락 선택
