### ISSUE TITLE
parsing과 reqeust_mesage 수정 요청 (토론 먼저 해봐요~ㅎㅎ)

### ISSUE THREAD

**Issue by aLVINlEE9** [keonwoo98/webserv#91]
request parsing 하는 과정에서 request 자체가 잘못되었을 경우 
여러 에러 케이스들을 request_message.getState로 얻어 올 수 있게 request_parsing_state를 만들어주셨으면 좋겠어요

**Comment by zhy2on** [comment]
request 자체가 잘못되었을 경우 400 bad request로 반환되게 됩니다
애초에 response에 status code넘겨줄 때 에러 코드로 반환 되기 대문에 따로 parsing_state를 만들어야 하나? 싶긴 한데
어떨 때 사용하려고 하시나요?

**Comment by aLVINlEE9** [comment]
아 그럼 그 경우에 request 의 state는 어떤식으로 반환되나요?

**Comment by aLVINlEE9** [comment]
try () {
} catch () {
}
로 해결이 가능하네요 ㅋㅋ

**Comment by u-lo-l** [comment]
request에서 status_code를 가지고 있어서 정상적으로 파싱되면 100이고 오류가 있으면 4×× 혹은 5xx로 status_code가 설정되고 GetStatusCode로 확잌 할 수 있어요

**Comment by aLVINlEE9** [comment]
넵 다들 감사합니다! 😄
