### ISSUE TITLE
Disconnect시 SegFault발생.

### ISSUE THREAD

**Issue by u-lo-l** [keonwoo98/webserv#98]
- Disconnect시 Segfault가 발생합니다. 확인 가능하신 분 확인 부탁드릴게요
- 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/60467872/209548524-dc4eaa8d-d150-4179-9d20-3131cd1394ae.png">

**Comment by u-lo-l** [comment]
ps. WebServ::StartServer()함수 이름 WebServ::Run() 혹은 WebServ::RunServer()로 변경하는 것 어떤가요

**Comment by u-lo-l** [comment]
#96 여기서 ClientSocket소멸자 기능을 제거해서 fd가 close되지 않아 생겼던 문제였습니다. close()추가하니 우선 해결 됐네요 @aLVINlEE9 
<img width="595" alt="image" src="https://user-images.githubusercontent.com/60467872/209548903-cab72872-0ff2-4895-9740-1128d7e559f6.png">

**Comment by minjune8506** [comment]
delete user_data 하면 client socket이 자동으로 닫히지 않나요??
어떤 부분이 문제였을까요
